backend:
  name: github
  repo: daviddarx/tinabeerli

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "home"
    label: "Home"
    create: false
    delete: false
    folder: "content/"
    slug: "home"
    extension: "json"
    format: "json"
    summary: "Version: {{version}} - {{title}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Content"
        name: "content"
        widget: "markdown"
        buttons:
          - bold
          - link

  - name: "beratung"
    label: "Beratung"
    create: false
    delete: false
    folder: "content/"
    slug: "beratung"
    extension: "json"
    format: "json"
    summary: "Version: {{version}} - {{title}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Content"
        name: "content"
        widget: "list"
        required: false
        fields:
          - label: "Text Content"
            name: "textcontent"
            required: false
            widget: "markdown"
            buttons:
              - bold
              - link
              - heading-three
              - bulleted-list
          - label: "List Content"
            name: "listcontent"
            widget: "list"
            required: false
            fields:
              - label: "Definition List"
                name: "definitionlist"
                widget: "object"
                required: false
                fields:
                  - label: "Title"
                    name: "title"
                    widget: "string"
                    required: false

                  - label: "Description"
                    name: "desc"
                    widget: "markdown"
                    required: false
                    buttons:
                    - bold
                    - link

  - name: "uebermich"
    label: "Über mich"
    create: true
    delete: true
    folder: "content/"
    slug: "uebermich"
    extension: "json"
    format: "json"
    summary: "Version: {{version}} - {{title}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Content"
        name: "content"
        widget: "markdown"
        buttons:
          - bold
          - link
          - heading-three
          - bulleted-list
