backend:
  name: github
  repo: daviddarx/tinabeerli

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "home_de"
    label: "Home DE"
    create: false
    delete: false
    folder: "content/home_de/"
    slug: "home_de"
    extension: "json"
    format: "json"
    summary: "Version: {{version}} - {{title}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Content"
        name: "content"
        widget: "markdown"
        buttons:
          - bold
          - link
          - heading-three
          - bulleted-list

  - name: "home_fr"
    label: "Home FR"
    create: false
    delete: false
    folder: "content/home_fr/"
    slug: "home_fr"
    extension: "json"
    format: "json"
    summary: "Version: {{version}} - {{title}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Content"
        name: "content"
        widget: "markdown"
        buttons:
          - bold
          - link
          - heading-three
          - bulleted-list

  - name: "beratung_de"
    label: "Beratung DE"
    create: false
    delete: false
    folder: "content/beratung_de/"
    slug: "beratung_de"
    extension: "json"
    format: "json"
    summary: "Version: {{version}} - {{title}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Content"
        name: "content"
        widget: "list"
        required: false
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Text Content"
            name: "textcontent"
            required: false
            widget: "markdown"
            buttons:
              - bold
              - link
              - heading-three
              - bulleted-list
          - label: "List Content"
            name: "listcontent"
            widget: "list"
            required: false
            fields:
              - label: "Definition List"
                name: "definitionlist"
                widget: "object"
                required: false
                fields:
                  - label: "Title"
                    name: "title"
                    widget: "string"
                    required: false

                  - label: "Description"
                    name: "desc"
                    widget: "markdown"
                    required: false
                    buttons:
                    - bold
                    - link

  - name: "beratung_fr"
    label: "Beratung FR"
    create: false
    delete: false
    folder: "content/beratung_fr/"
    slug: "beratung_fr"
    extension: "json"
    format: "json"
    summary: "Version: {{version}} - {{title}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Content"
        name: "content"
        widget: "list"
        required: false
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Text Content"
            name: "textcontent"
            required: false
            widget: "markdown"
            buttons:
              - bold
              - link
              - heading-three
              - bulleted-list
          - label: "List Content"
            name: "listcontent"
            widget: "list"
            required: false
            fields:
              - label: "Definition List"
                name: "definitionlist"
                widget: "object"
                required: false
                fields:
                  - label: "Title"
                    name: "title"
                    widget: "string"
                    required: false

                  - label: "Description"
                    name: "desc"
                    widget: "markdown"
                    required: false
                    buttons:
                    - bold
                    - link

  - name: "uebermich_de"
    label: "Über mich DE"
    create: false
    delete: false
    folder: "content/uebermich_de/"
    slug: "uebermich_de"
    extension: "json"
    format: "json"
    summary: "Version: {{version}} - {{title}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Content"
        name: "content"
        widget: "markdown"
        buttons:
          - bold
          - link
          - heading-three
          - bulleted-list

  - name: "uebermich_fr"
    label: "Über mich FR"
    create: false
    delete: false
    folder: "content/uebermich_fr/"
    slug: "uebermich_fr"
    extension: "json"
    format: "json"
    summary: "Version: {{version}} - {{title}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Content"
        name: "content"
        widget: "markdown"
        buttons:
          - bold
          - link
          - heading-three
          - bulleted-list
