backend:
  name: github
  repo: daviddarx/tinabeerli

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "specialAnnouncement"
    label: "Special Announcement"
    create: false
    delete: false
    folder: "_content/specialAnnouncement"
    slug: "specialannouncement"
    extension: "json"
    format: "json"
    summary: "Version: {{version}} - {{title}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Button Title"
        name: "buttonTitle"
        widget: "string"

      - label: "Description"
        name: "desc"
        widget: "markdown"
        buttons:
          - bold
          - italic
          - link
